// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClNy_uAztEiiwVgZi1eH35GTdzK0syJYo',
    appId: '1:993604068634:web:e85c5f2f98e15e12b578a3',
    messagingSenderId: '993604068634',
    projectId: 'login-gui-1',
    authDomain: 'login-gui-1.firebaseapp.com',
    storageBucket: 'login-gui-1.firebasestorage.app',
    measurementId: 'G-QYVBQK63RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeeXi3psoV6VJa_fAbcKby2zTrwxvYS2A',
    appId: '1:676634783268:android:0912c259c4add96a7972b1',
    messagingSenderId: '676634783268',
    projectId: 'taska-database-cb9c3',
    storageBucket: 'taska-database-cb9c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC69lz8WuifH0VZP20U7QO2E-KUgzg5puc',
    appId: '1:676634783268:ios:65efdfead341c9607972b1',
    messagingSenderId: '676634783268',
    projectId: 'taska-database-cb9c3',
    storageBucket: 'taska-database-cb9c3.firebasestorage.app',
    iosBundleId: 'com.example.taskaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGEBox8qpfCHoHLKqRhzRhpD0zltlRDso',
    appId: '1:993604068634:ios:ff016cb2dd1c1acbb578a3',
    messagingSenderId: '993604068634',
    projectId: 'login-gui-1',
    storageBucket: 'login-gui-1.firebasestorage.app',
    iosBundleId: 'com.example.taskaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClNy_uAztEiiwVgZi1eH35GTdzK0syJYo',
    appId: '1:993604068634:web:4e1b2b4a42d8632eb578a3',
    messagingSenderId: '993604068634',
    projectId: 'login-gui-1',
    authDomain: 'login-gui-1.firebaseapp.com',
    storageBucket: 'login-gui-1.firebasestorage.app',
    measurementId: 'G-Z2RLE2D77S',
  );
}